### ISSUE TITLE
python setup.py develop报错

### ISSUE THREAD

**Issue by Fan123456-c** [dragonfly606/MonoCD#11]
想学习一下大佬优秀的工作，但是磕磕绊绊安装完库后，在编译monocd使用python setup.py develop时报错，求解决：
running develop
/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/command/develop.py:39: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running egg_info
writing monocd.egg-info/PKG-INFO
writing dependency_links to monocd.egg-info/dependency_links.txt
writing top-level names to monocd.egg-info/top_level.txt
reading manifest file 'monocd.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'monocd.egg-info/SOURCES.txt'
running build_ext
building '_ext' extension
Emitting ninja build file /data0/lfan/Other_distill/MonoCD/original/build/temp.linux-x86_64-cpython-37/build.ninja...
Traceback (most recent call last):
  File "setup.py", line 67, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/command/develop.py", line 33, in run
    self.install_for_development()
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/command/develop.py", line 108, in install_for_development
    self.run_command('build_ext')
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 88, in run
    _build_ext.run(self)
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
    build_ext.build_extensions(self)
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 555, in build_extension
    depends=ext.depends,
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 595, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1484, in _write_ninja_file_and_compile_objects
    with_cuda=with_cuda)
  File "/home/lfan/.conda/envs/monocd/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 2014, in _write_ninja_file
    assert len(sources) > 0
AssertionError

**Comment by Fan123456-c** [comment]
貌似原因是setup.py中没有找到这三个文件：
![image](https://github.com/user-attachments/assets/56da9db2-0a39-461a-b93e-d48d1893735a)

**Comment by Fan123456-c** [comment]
> 貌似原因是setup.py中没有找到这三个文件： ![image](https://private-user-images.githubusercontent.com/71744088/395603558-56da9db2-0a39-461a-b93e-d48d1893735a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMDI0NjEsIm5iZiI6MTczNDEwMjE2MSwicGF0aCI6Ii83MTc0NDA4OC8zOTU2MDM1NTgtNTZkYTlkYjItMGEzOS00NjFhLWI5M2UtZDQ4ZDE4OTM3MzVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDE1MDI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhN2RlZTM0ZTI5MGU1YWRhMTgxMDM3MGY5MDRmYTc0N2U2MmZjMmY3ZTA1NzUzMjdjODljNjBlZGE5N2EyNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.R6PqvfDl8dD_mqRxvi416TMNrSXh2V0Q33Htli6liFA)

目录中没有提供“csrc”的文件

**Comment by tranquan687** [comment]
have you solved it? i got the same problem

**Comment by Fan123456-c** [comment]
> have you solved it? i got the same problem

Not yet

**Comment by dragonfly606** [comment]
@Fan123456-c @tranquan687 Thank you for your attention. I reproduced this problem when installing under pytorch1.7, but it did not happen when installing under pytorch1.4, so I speculate that it is a problem with the pytorch version. Commenting out [this line](https://github.com/dragonfly606/MonoCD/blob/f8e8dc5d620b1e2d6b97debbd2426554e07168eb/setup.py#L65) can temporarily solve it.

**Comment by Fan123456-c** [comment]
> @Fan123456-c @tranquan687 Thank you for your attention. I reproduced this problem when installing under pytorch1.7, but it did not happen when installing under pytorch1.4, so I speculate that it is a problem with the pytorch version. Commenting out [this line](https://github.com/dragonfly606/MonoCD/blob/f8e8dc5d620b1e2d6b97debbd2426554e07168eb/setup.py#L65) can temporarily solve it.

solved it. Thanks a lot.

**Comment by Jerry9824** [comment]
> > [@Fan123456-c](https://github.com/Fan123456-c) [@tranquan687](https://github.com/tranquan687) Thank you for your attention. I reproduced this problem when installing under pytorch1.7, but it did not happen when installing under pytorch1.4, so I speculate that it is a problem with the pytorch version. Commenting out [this line](https://github.com/dragonfly606/MonoCD/blob/f8e8dc5d620b1e2d6b97debbd2426554e07168eb/setup.py#L65) can temporarily solve it.
> 
> solved it. Thanks a lot.

Hello, may I ask how you solved this problem?
